[package]
authors = ["Architect Financial Technologies LLC"]
description = "Architect.xyz trading platform API and SDK"
documentation = "https://docs.rs/does-not-exist"
homepage = "https://www.architect.xyz"
license = "AGPL-3.0-only"
name = "demon-api"
version = "6.6.6"
edition = "2021"
keywords = ["crypto", "hft", "trading", "finance"]
categories = ["finance", "cryptography::cryptocurrencies"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
arcstr = { version = "1", features = ["serde"] }
base64 = "0.21"
bytes = "1"
chrono = { version = "^0.4.24", features = ["serde"] }
compact_str = { version = "0.7.0", features = ["serde"] }
derive = { package = "demon_derive", version = "6.6.6", path = "../derive" }
futures = "0.3"
futures-util = "0.3"
hmac = "0.12"
log = "0.4.20"
netidx = { version = "0.26.0" }
netidx-core = { version = "0.26.0" }
netidx-derive = { version = "0.22.0" }
once_cell = "1"
rust_decimal = { version = "1", features = ["maths", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
sha2 = "0.10"
time = { version = "0.3.20", features = ["serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros", "io-std", "io-util"] }
uuid = { version = "1", features = ["v4", "v5", "serde"] }