[package]
authors = ["Architect Financial Technologies LLC"]
description = "Architect.xyz Trading Platform API"
documentation = "https://docs.rs/does-not-exist"
homepage = "https://www.architect.xyz"
license = "AGPL-3.0-only"
name = "architect-api"
version = "0.2.0"
edition = "2021"
keywords = ["crypto", "hft", "trading", "finance"]
categories = ["finance", "cryptography::cryptocurrencies"]

[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
derive = { package = "architect-derive", version = "0.2.0", path = "../derive" }
dirs = { workspace = true }
either = { workspace = true }
enumflags2 = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
fxhash = { workspace = true }
hmac = { workspace = true }
log = { workspace = true }
netidx = { workspace = true }
netidx-core = { workspace = true }
netidx-derive = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
portable-atomic = { workspace = true }
rand = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }